修改 workflow 配置文件

diff --git a/.github/workflows/hugo.yml b/.github/workflows/hugo.yml
--- a/.github/workflows/hugo.yml
+++ b/.github/workflows/hugo.yml
@@ -20,16 +20,16 @@ jobs:
     env:
       HUGO_VERSION: 0.122.0
     steps:
-      - name: 🧹 Clean up diag logs and check disk space
-        run: |
-          echo "::group::清理 diag 日志缓存"
-          # sudo rm -rf /home/runner/actions-runner/cached/_diag/* || true
-          echo "清理完成"
-          echo "::endgroup::"
+      # - name: 🧹 Clean up diag logs and check disk space
+      #   run: |
+      #     echo "::group::清理 diag 日志缓存"
+      #     # sudo rm -rf /home/runner/actions-runner/cached/_diag/* || true
+      #     echo "清理完成"
+      #     echo "::endgroup::"
 
-          echo "::group::检查当前磁盘空间"
-          df -h
-          echo "::endgroup::"
+      #     echo "::group::检查当前磁盘空间"
+      #     df -h
+      #     echo "::endgroup::"
 
       - name: 📦 Install Hugo CLI
         run: |
