修改 workflow 配置文件

diff --git a/.github/workflows/hugo.yml b/.github/workflows/hugo.yml
--- a/.github/workflows/hugo.yml
+++ b/.github/workflows/hugo.yml
@@ -21,11 +21,11 @@ jobs:
     env:
       HUGO_VERSION: 0.122.0
     steps:
-      - name: Clean up disk space (before build)
-        run: |
-          echo "清理缓存文件..."
-          sudo rm -rf /home/runner/actions-runner/cached/_diag/* || true
-          df -h
+      # - name: Clean up disk space (before build)
+      #   run: |
+      #     echo "清理缓存文件..."
+      #     sudo rm -rf /home/runner/actions-runner/cached/_diag/* || true
+      #     df -h
 
       - name: Install Hugo CLI
         run: |
